/*

 BIRDANDPIPES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 8 x 16
  Tiles                : 0 to 17

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __BirdAndPipes_h_INCLUDE
#define __BirdAndPipes_h_INCLUDE

/* Bank of tiles. */
#define BirdAndPipesBank 0

/* Super Gameboy palette 0 */
#define BirdAndPipesSGBPal0c0 6076
#define BirdAndPipesSGBPal0c1 8935
#define BirdAndPipesSGBPal0c2 6596
#define BirdAndPipesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BirdAndPipesSGBPal1c0 6076
#define BirdAndPipesSGBPal1c1 8935
#define BirdAndPipesSGBPal1c2 6596
#define BirdAndPipesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BirdAndPipesSGBPal2c0 6076
#define BirdAndPipesSGBPal2c1 8935
#define BirdAndPipesSGBPal2c2 6596
#define BirdAndPipesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BirdAndPipesSGBPal3c0 6076
#define BirdAndPipesSGBPal3c1 8935
#define BirdAndPipesSGBPal3c2 6596
#define BirdAndPipesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BirdAndPipesCGBPal0c0 32767
#define BirdAndPipesCGBPal0c1 9119
#define BirdAndPipesCGBPal0c2 500
#define BirdAndPipesCGBPal0c3 1229

/* Gameboy Color palette 1 */
#define BirdAndPipesCGBPal1c0 32767
#define BirdAndPipesCGBPal1c1 834
#define BirdAndPipesCGBPal1c2 21464
#define BirdAndPipesCGBPal1c3 1185

/* Gameboy Color palette 2 */
#define BirdAndPipesCGBPal2c0 6076
#define BirdAndPipesCGBPal2c1 8935
#define BirdAndPipesCGBPal2c2 6596
#define BirdAndPipesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BirdAndPipesCGBPal3c0 6076
#define BirdAndPipesCGBPal3c1 8935
#define BirdAndPipesCGBPal3c2 6596
#define BirdAndPipesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BirdAndPipesCGBPal4c0 6076
#define BirdAndPipesCGBPal4c1 8935
#define BirdAndPipesCGBPal4c2 6596
#define BirdAndPipesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BirdAndPipesCGBPal5c0 6076
#define BirdAndPipesCGBPal5c1 8935
#define BirdAndPipesCGBPal5c2 6596
#define BirdAndPipesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BirdAndPipesCGBPal6c0 6076
#define BirdAndPipesCGBPal6c1 8935
#define BirdAndPipesCGBPal6c2 6596
#define BirdAndPipesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BirdAndPipesCGBPal7c0 6076
#define BirdAndPipesCGBPal7c1 8935
#define BirdAndPipesCGBPal7c2 6596
#define BirdAndPipesCGBPal7c3 5344

/* CGB palette entries. */
#define BirdAndPipesCGB0 0
#define BirdAndPipesCGB1 0
#define BirdAndPipesCGB2 0
#define BirdAndPipesCGB3 0
#define BirdAndPipesCGB4 0
#define BirdAndPipesCGB5 0
#define BirdAndPipesCGB6 0
#define BirdAndPipesCGB7 0
#define BirdAndPipesCGB8 0
#define BirdAndPipesCGB9 0
#define BirdAndPipesCGB10 1
#define BirdAndPipesCGB11 1
#define BirdAndPipesCGB12 1
#define BirdAndPipesCGB13 1
#define BirdAndPipesCGB14 1
#define BirdAndPipesCGB15 1
#define BirdAndPipesCGB16 1
#define BirdAndPipesCGB17 1
/* Start of tile array. */
extern const unsigned char BirdAndPipes[];
#define BirdAndPipesLen 36

#endif

/* End of BIRDANDPIPES.H */
