//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_FlappyBirdTitle_H
#define METASPRITE_FlappyBirdTitle_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define FlappyBirdTitle_TILE_H 8
#define FlappyBirdTitle_WIDTH 96
#define FlappyBirdTitle_HEIGHT 32
#define FlappyBirdTitle_TILE_COUNT 36
#define FlappyBirdTitle_MAP_ATTRIBUTES FlappyBirdTitle_map_attributes
#define FlappyBirdTitle_TILE_PALS 0

BANKREF_EXTERN(FlappyBirdTitle)

extern const palette_color_t FlappyBirdTitle_palettes[12];
extern const uint8_t FlappyBirdTitle_tiles[576];

extern const unsigned char FlappyBirdTitle_map[48];
extern const unsigned char FlappyBirdTitle_map_attributes[48];

#endif