//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_FlappyBirdMedals_H
#define METASPRITE_FlappyBirdMedals_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define FlappyBirdMedals_TILE_H 16
#define FlappyBirdMedals_WIDTH 32
#define FlappyBirdMedals_HEIGHT 32
#define FlappyBirdMedals_TILE_COUNT 13
#define FlappyBirdMedals_PIVOT_X 16
#define FlappyBirdMedals_PIVOT_Y 16
#define FlappyBirdMedals_PIVOT_W 32
#define FlappyBirdMedals_PIVOT_H 32

BANKREF_EXTERN(FlappyBirdMedals)

extern const palette_color_t FlappyBirdMedals_palettes[16];
extern const uint8_t FlappyBirdMedals_tiles[416];

extern const metasprite_t* const FlappyBirdMedals_metasprites[4];

#endif