//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_FlappyBirdBackground_H
#define METASPRITE_FlappyBirdBackground_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define FlappyBirdBackground_TILE_H 8
#define FlappyBirdBackground_WIDTH 256
#define FlappyBirdBackground_HEIGHT 144
#define FlappyBirdBackground_TILE_COUNT 63
#define FlappyBirdBackground_MAP_ATTRIBUTES FlappyBirdBackground_map_attributes
#define FlappyBirdBackground_TILE_PALS 0

BANKREF_EXTERN(FlappyBirdBackground)

extern const palette_color_t FlappyBirdBackground_palettes[12];
extern const uint8_t FlappyBirdBackground_tiles[1008];

extern const unsigned char FlappyBirdBackground_map[576];
extern const unsigned char FlappyBirdBackground_map_attributes[576];

#endif