//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_FlappyBirdEnd_H
#define METASPRITE_FlappyBirdEnd_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define FlappyBirdEnd_TILE_H 8
#define FlappyBirdEnd_WIDTH 112
#define FlappyBirdEnd_HEIGHT 56
#define FlappyBirdEnd_TILE_COUNT 27
#define FlappyBirdEnd_MAP_ATTRIBUTES FlappyBirdEnd_map_attributes
#define FlappyBirdEnd_TILE_PALS 0

BANKREF_EXTERN(FlappyBirdEnd)

extern const palette_color_t FlappyBirdEnd_palettes[8];
extern const uint8_t FlappyBirdEnd_tiles[432];

extern const unsigned char FlappyBirdEnd_map[98];
extern const unsigned char FlappyBirdEnd_map_attributes[98];

#endif