/*

 GROUNDTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 11

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define GroundTilesBank 0

/* Super Gameboy palette 0 */
#define GroundTilesSGBPal0c0 6076
#define GroundTilesSGBPal0c1 8935
#define GroundTilesSGBPal0c2 6596
#define GroundTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define GroundTilesSGBPal1c0 6076
#define GroundTilesSGBPal1c1 8935
#define GroundTilesSGBPal1c2 6596
#define GroundTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define GroundTilesSGBPal2c0 6076
#define GroundTilesSGBPal2c1 8935
#define GroundTilesSGBPal2c2 6596
#define GroundTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define GroundTilesSGBPal3c0 6076
#define GroundTilesSGBPal3c1 8935
#define GroundTilesSGBPal3c2 6596
#define GroundTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define GroundTilesCGBPal0c0 20382
#define GroundTilesCGBPal0c1 20438
#define GroundTilesCGBPal0c2 742
#define GroundTilesCGBPal0c3 1258

/* Gameboy Color palette 1 */
#define GroundTilesCGBPal1c0 20382
#define GroundTilesCGBPal1c1 32767
#define GroundTilesCGBPal1c2 1224
#define GroundTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define GroundTilesCGBPal2c0 6076
#define GroundTilesCGBPal2c1 8935
#define GroundTilesCGBPal2c2 6596
#define GroundTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define GroundTilesCGBPal3c0 6076
#define GroundTilesCGBPal3c1 8935
#define GroundTilesCGBPal3c2 6596
#define GroundTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define GroundTilesCGBPal4c0 6076
#define GroundTilesCGBPal4c1 8935
#define GroundTilesCGBPal4c2 6596
#define GroundTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define GroundTilesCGBPal5c0 6076
#define GroundTilesCGBPal5c1 8935
#define GroundTilesCGBPal5c2 6596
#define GroundTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define GroundTilesCGBPal6c0 6076
#define GroundTilesCGBPal6c1 8935
#define GroundTilesCGBPal6c2 6596
#define GroundTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define GroundTilesCGBPal7c0 6076
#define GroundTilesCGBPal7c1 8935
#define GroundTilesCGBPal7c2 6596
#define GroundTilesCGBPal7c3 5344

/* CGB palette entries. */
#define GroundTilesCGB0 0
#define GroundTilesCGB1 1
#define GroundTilesCGB2 1
#define GroundTilesCGB3 1
#define GroundTilesCGB4 1
#define GroundTilesCGB5 1
#define GroundTilesCGB6 1
#define GroundTilesCGB7 1
#define GroundTilesCGB8 1
#define GroundTilesCGB9 1
#define GroundTilesCGB10 1
#define GroundTilesCGB11 1
/* Start of tile array. */
extern unsigned char GroundTiles[];

/* End of GROUNDTILES.H */
