/*

 MENUSPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __MenuSprites_h_INCLUDE
#define __MenuSprites_h_INCLUDE

/* Bank of tiles. */
#define MenuSpritesBank 0

/* Super Gameboy palette 0 */
#define MenuSpritesSGBPal0c0 6076
#define MenuSpritesSGBPal0c1 8935
#define MenuSpritesSGBPal0c2 6596
#define MenuSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define MenuSpritesSGBPal1c0 6076
#define MenuSpritesSGBPal1c1 8935
#define MenuSpritesSGBPal1c2 6596
#define MenuSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define MenuSpritesSGBPal2c0 6076
#define MenuSpritesSGBPal2c1 8935
#define MenuSpritesSGBPal2c2 6596
#define MenuSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define MenuSpritesSGBPal3c0 6076
#define MenuSpritesSGBPal3c1 8935
#define MenuSpritesSGBPal3c2 6596
#define MenuSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define MenuSpritesCGBPal0c0 7399
#define MenuSpritesCGBPal0c1 26425
#define MenuSpritesCGBPal0c2 32767
#define MenuSpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define MenuSpritesCGBPal1c0 32767
#define MenuSpritesCGBPal1c1 17360
#define MenuSpritesCGBPal1c2 9450
#define MenuSpritesCGBPal1c3 21469

/* Gameboy Color palette 2 */
#define MenuSpritesCGBPal2c0 0
#define MenuSpritesCGBPal2c1 32767
#define MenuSpritesCGBPal2c2 5311
#define MenuSpritesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define MenuSpritesCGBPal3c0 6076
#define MenuSpritesCGBPal3c1 8935
#define MenuSpritesCGBPal3c2 6596
#define MenuSpritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define MenuSpritesCGBPal4c0 6076
#define MenuSpritesCGBPal4c1 8935
#define MenuSpritesCGBPal4c2 6596
#define MenuSpritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define MenuSpritesCGBPal5c0 6076
#define MenuSpritesCGBPal5c1 8935
#define MenuSpritesCGBPal5c2 6596
#define MenuSpritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define MenuSpritesCGBPal6c0 6076
#define MenuSpritesCGBPal6c1 8935
#define MenuSpritesCGBPal6c2 6596
#define MenuSpritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define MenuSpritesCGBPal7c0 6076
#define MenuSpritesCGBPal7c1 8935
#define MenuSpritesCGBPal7c2 6596
#define MenuSpritesCGBPal7c3 5344

/* SGB palette entries. */
#define MenuSpritesSGB0 0
#define MenuSpritesSGB1 0
/* Start of tile array. */
extern const unsigned char MenuSprites[];
#define MenuSpritesLen 8

#endif

/* End of MENUSPRITES.H */
