/*

 SCORETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 9

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ScoreTiles_h_INCLUDE
#define __ScoreTiles_h_INCLUDE

/* Bank of tiles. */
#define ScoreTilesBank 0

/* Super Gameboy palette 0 */
#define ScoreTilesSGBPal0c0 6076
#define ScoreTilesSGBPal0c1 8935
#define ScoreTilesSGBPal0c2 6596
#define ScoreTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ScoreTilesSGBPal1c0 6076
#define ScoreTilesSGBPal1c1 8935
#define ScoreTilesSGBPal1c2 6596
#define ScoreTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ScoreTilesSGBPal2c0 6076
#define ScoreTilesSGBPal2c1 8935
#define ScoreTilesSGBPal2c2 6596
#define ScoreTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ScoreTilesSGBPal3c0 6076
#define ScoreTilesSGBPal3c1 8935
#define ScoreTilesSGBPal3c2 6596
#define ScoreTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ScoreTilesCGBPal0c0 20382
#define ScoreTilesCGBPal0c1 20438
#define ScoreTilesCGBPal0c2 742
#define ScoreTilesCGBPal0c3 1258

/* Gameboy Color palette 1 */
#define ScoreTilesCGBPal1c0 20382
#define ScoreTilesCGBPal1c1 32767
#define ScoreTilesCGBPal1c2 1224
#define ScoreTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define ScoreTilesCGBPal2c0 6076
#define ScoreTilesCGBPal2c1 8935
#define ScoreTilesCGBPal2c2 6596
#define ScoreTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define ScoreTilesCGBPal3c0 6076
#define ScoreTilesCGBPal3c1 8935
#define ScoreTilesCGBPal3c2 6596
#define ScoreTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define ScoreTilesCGBPal4c0 6076
#define ScoreTilesCGBPal4c1 8935
#define ScoreTilesCGBPal4c2 6596
#define ScoreTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define ScoreTilesCGBPal5c0 6076
#define ScoreTilesCGBPal5c1 8935
#define ScoreTilesCGBPal5c2 6596
#define ScoreTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define ScoreTilesCGBPal6c0 6076
#define ScoreTilesCGBPal6c1 8935
#define ScoreTilesCGBPal6c2 6596
#define ScoreTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define ScoreTilesCGBPal7c0 6076
#define ScoreTilesCGBPal7c1 8935
#define ScoreTilesCGBPal7c2 6596
#define ScoreTilesCGBPal7c3 5344

/* CGB palette entries. */
#define ScoreTilesCGB0 0
#define ScoreTilesCGB1 1
#define ScoreTilesCGB2 1
#define ScoreTilesCGB3 1
#define ScoreTilesCGB4 1
#define ScoreTilesCGB5 1
#define ScoreTilesCGB6 1
#define ScoreTilesCGB7 1
#define ScoreTilesCGB8 1
#define ScoreTilesCGB9 1
/* Start of tile array. */
extern const unsigned char ScoreTiles[];
#define ScoreTilesLen 10

#endif

/* End of SCORETILES.H */
