/*

 TAPTOSTARTSPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : Constant per entry.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __TapToStartSprites_h_INCLUDE
#define __TapToStartSprites_h_INCLUDE

/* Bank of tiles. */
#define TapToStartSpritesBank 0

/* Super Gameboy palette 0 */
#define TapToStartSpritesSGBPal0c0 6076
#define TapToStartSpritesSGBPal0c1 8935
#define TapToStartSpritesSGBPal0c2 6596
#define TapToStartSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TapToStartSpritesSGBPal1c0 6076
#define TapToStartSpritesSGBPal1c1 8935
#define TapToStartSpritesSGBPal1c2 6596
#define TapToStartSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TapToStartSpritesSGBPal2c0 6076
#define TapToStartSpritesSGBPal2c1 8935
#define TapToStartSpritesSGBPal2c2 6596
#define TapToStartSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TapToStartSpritesSGBPal3c0 6076
#define TapToStartSpritesSGBPal3c1 8935
#define TapToStartSpritesSGBPal3c2 6596
#define TapToStartSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TapToStartSpritesCGBPal0c0 7399
#define TapToStartSpritesCGBPal0c1 26425
#define TapToStartSpritesCGBPal0c2 32767
#define TapToStartSpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TapToStartSpritesCGBPal1c0 32767
#define TapToStartSpritesCGBPal1c1 17360
#define TapToStartSpritesCGBPal1c2 9450
#define TapToStartSpritesCGBPal1c3 21469

/* Gameboy Color palette 2 */
#define TapToStartSpritesCGBPal2c0 0
#define TapToStartSpritesCGBPal2c1 32767
#define TapToStartSpritesCGBPal2c2 5311
#define TapToStartSpritesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TapToStartSpritesCGBPal3c0 6076
#define TapToStartSpritesCGBPal3c1 8935
#define TapToStartSpritesCGBPal3c2 6596
#define TapToStartSpritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TapToStartSpritesCGBPal4c0 6076
#define TapToStartSpritesCGBPal4c1 8935
#define TapToStartSpritesCGBPal4c2 6596
#define TapToStartSpritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TapToStartSpritesCGBPal5c0 6076
#define TapToStartSpritesCGBPal5c1 8935
#define TapToStartSpritesCGBPal5c2 6596
#define TapToStartSpritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TapToStartSpritesCGBPal6c0 6076
#define TapToStartSpritesCGBPal6c1 8935
#define TapToStartSpritesCGBPal6c2 6596
#define TapToStartSpritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TapToStartSpritesCGBPal7c0 6076
#define TapToStartSpritesCGBPal7c1 8935
#define TapToStartSpritesCGBPal7c2 6596
#define TapToStartSpritesCGBPal7c3 5344

/* SGB palette entries. */
#define TapToStartSpritesSGB0 0
#define TapToStartSpritesSGB1 0
/* Start of tile array. */
extern const unsigned char TapToStartSprites[];
#define TapToStartSpritesLen 8

#endif

/* End of TAPTOSTARTSPRITES.H */
